/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week9.bikeapp;
import javax.swing.DefaultListModel;
/**
 *
 * @author ryanwhite
 */
public class BikeAppGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BikeAppGUI.class.getName());
    StationSLL stations = new StationSLL();
    UserQueueInterface uq = new UserQueue();
    ReturnBikeStack ebike = new ReturnBikeStack();
    ReturnBikeStack bike = new ReturnBikeStack();
    private boolean bookedAlready=false;
    DefaultListModel<String> station1=new DefaultListModel<>();

    /**
     * Creates new form BikeAppGUI
     */
    public BikeAppGUI() {
        initComponents();
        displayADTs();
        updatedADTs();
        addLists();
        buttonGroup1.add(eBikeBtn);
        buttonGroup1.add(normalBikeBtn);
    }
    
    //loads data into the queue,single linked list and stack
    public void displayADTs() {
        //User Queue
        uq.enqueue("Jack Malone, #12467, Electric Bike, 3 Arena");
        uq.enqueue("Sarah King, #32144, Normal Bike, NCI Spenser Dock");
        uq.enqueue("Thomas Smith, #464785, Electric Bike, Grand canal");
        uq.enqueue("Claire Kelly, #789292, Normal Bike, 3 Arena");
        uq.enqueue("Ben Thompson, #1535262, Electric Bike, NCI Spenser Dock");

        //Station Single linked list
        Station s1 = new Station(1,"NCI Spenser Dock", 12,2);
        stations.add(s1);
        Station s2 = new Station(2,"3 Arena",2,1);
        stations.add(s2);
        Station s3 = new Station(3,"Connolly Station",15,4);
        stations.add(s3);
        Station s4 = new Station(4,"Samuel Beckett Bridge",5,3);
        stations.add(s4);
        Station s5 = new Station(5,"Grand Canal",3,5);
        stations.add(s5);
        Station s6 = new Station(6,"The Spire",25,6);
        stations.add(s6);
        Station s7 = new Station(7,"Grafton Street",32,7);
        stations.add(s7);
        Station s8 = new Station(8,"Stephens Green",12,8);
        stations.add(s8);
        Station s9 = new Station(9,"Phoenix Park",1,12);
        stations.add(s9);
        Station s10 = new Station(10,"Croke Park",4,6);
        stations.add(s10);
        

        //Electric Bike Stack
        ElectricBike ebike1 = new ElectricBike(111345, "NCI Spenser Dock");
        ebike.push(ebike1);
        ElectricBike ebike2 = new ElectricBike(111321, "NCI Spenser Dock");
        ebike.push(ebike2);
        

        //Normal Bike Stack
        NormalBike bike1 = new NormalBike(121245, "NCI Spenser Dock");
        bike.push(bike1);
        NormalBike bike2 = new NormalBike(128745, "Stephens Green");
        bike.push(bike2);
    }
    
    //this updates when the user presses the book button
    private void updatedADTs() {
        //User Queue
        currentQueueArea.setText("People waiting for bikes:\n "+uq.size());
        //Bike Stack
        bikeList.setText("Electric Bikes:\n " + ebike.displayStack()+"Normal Bikes:\n "+bike.displayStack());
    }
    
    //this method adds the single linked list to the list model to display it
    //used same SLL for both start and end of journey
    public void addLists(){
        for(int i=1; i <= stations.size();i++){
            Station s=(Station) stations.get(i);
            station1.addElement(s.getStationName());
        }
        stationList1.setModel(station1);
        stationList2.setModel(station1);
      
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stationList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stationList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        exitBtn = new javax.swing.JButton();
        eBikeBtn = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        currentQueueArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bikeList = new javax.swing.JTextArea();
        bookBike = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        normalBikeBtn = new javax.swing.JRadioButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel1.setText("Bike Dublin");

        jLabel2.setText("Please select a station from the drop down menu:");

        stationList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(stationList2);

        jLabel3.setText("Please select the bike type you would like:");

        jLabel4.setText("Please select a final destination:");

        stationList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(stationList1);

        textAreaOutput.setColumns(20);
        textAreaOutput.setRows(5);
        jScrollPane3.setViewportView(textAreaOutput);

        exitBtn.setText("Exit App");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        eBikeBtn.setText("Electric Bike");
        eBikeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBikeBtnActionPerformed(evt);
            }
        });

        currentQueueArea.setColumns(20);
        currentQueueArea.setRows(5);
        jScrollPane4.setViewportView(currentQueueArea);

        jLabel5.setText("Current Queue: ");

        bikeList.setColumns(20);
        bikeList.setRows(5);
        jScrollPane5.setViewportView(bikeList);

        bookBike.setText("Book Bike");
        bookBike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBikeActionPerformed(evt);
            }
        });

        jLabel6.setText("Bikes Available:");

        jLabel7.setText("Booking Details:");

        normalBikeBtn.setText("Normal Bike");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookBike)
                .addGap(80, 80, 80)
                .addComponent(exitBtn)
                .addGap(277, 277, 277))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eBikeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(normalBikeBtn))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(normalBikeBtn)
                            .addComponent(eBikeBtn))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(bookBike))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //exits the app
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void eBikeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBikeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eBikeBtnActionPerformed
    
    //manages booking process
    private void bookBikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBikeActionPerformed
        // TODO add your handling code here:
        //checks whether user has booked a bike in the current session of the app
        if(bookedAlready==true){
             textAreaOutput.setText("You have already booked a bike.");
             return;
        }
        //checks which radio button is pressed to determine which bike user wants
        String start=stationList1.getSelectedValue();
        String end=stationList2.getSelectedValue();
        if(start==null || end==null){
            textAreaOutput.setText("Please select a start and end to your journey to book a bike.");
            return;
        }
        if(start.equals(end)){
            textAreaOutput.setText("You cannot select the same station to start and end your journey.");
            return;
        }
        if(eBikeBtn.isSelected()){
            bookElectricBike(start,end);
        }else if(normalBikeBtn.isSelected()){
            bookNormalBike(start,end);
        }else{
            textAreaOutput.setText("Please select the type of bike you want.");
        }
    }//GEN-LAST:event_bookBikeActionPerformed
    private void bookElectricBike(String start,String end) {
        double PricePerKm=calCost(start,end);
        if (!ebike.isEmpty()) {
            Bike rentBike = ebike.pop();
            bookedAlready=true;
            textAreaOutput.setText("Electric Bike Rented:\nStarting point: "+start+"\nEnd point: "+end+"\nCost: €"+PricePerKm+"\nBike: "+rentBike);
            bookedAlready=true;              
        } else {
            uq.enqueue("New user added to queue for an electric bike\n");
            textAreaOutput.setText("No electric bikes available, user in queue\n");
        }
        updatedADTs();
    }
    
    //CalCost of journey
    private double calCost(String start,String end){
        Station st1= getStationByName(start);
        Station st2=getStationByName(end);
        
        int distance=(st1.getDistanceCal()*st2.getDistanceCal());
        double pricePerKm;
        if(eBikeBtn.isSelected()){
            pricePerKm=1.5;
        }else{
            pricePerKm=1.0;
        }
        return distance*pricePerKm;
    }
    
    private Station getStationByName(String name){
        for(int i=1; i <=stations.size();i++){
            Station st=(Station)stations.get(i);
            if(st.getStationName().equals(name)){
                return st;
            }
        }
        return null;
    }
    
    
    
    private void bookNormalBike(String start,String end) {
        if (!bike.isEmpty()) {
            double pricePerKm=calCost(start,end);
            Bike rentBike = bike.pop();
            textAreaOutput.setText("Normal Bike Rented:\nStarting point: "+start+"\nEnd point: "+end+"\nCost: €"+pricePerKm+"\nBike: "+rentBike);
            bookedAlready=true;
        } else {
            uq.enqueue("New user added to queue for a bike\n");
            textAreaOutput.setText("No bikes available, user in queue\n");
        }
        updatedADTs();
    }
    /**
     * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BikeAppGUI().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bikeList;
    private javax.swing.JButton bookBike;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextArea currentQueueArea;
    private javax.swing.JRadioButton eBikeBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton normalBikeBtn;
    private javax.swing.JList<String> stationList1;
    private javax.swing.JList<String> stationList2;
    private javax.swing.JTextArea textAreaOutput;
    // End of variables declaration//GEN-END:variables
}
